### ISSUE TITLE
Support using diffview for "entire git diff of the selected commit"

### ISSUE THREAD

**Issue by jemag** [aaronhallaert/advanced-git-search.nvim#23]
Currently doing `<C-e>` in `diff_commit_file` will open a terminal typing:
`git diff 426a273~ 426a273`
![image](https://user-images.githubusercontent.com/7985687/229310562-f10c930f-8839-4009-8b45-11dd1fdc2510.png)

I would like to be able to instead just open diffview as usual with something like `:DiffviewOpen -uno 426a273~..426a273` instead. This will provide the same differences between both commits across multiple files but in a more user-friendly way (or at least in my opinion).

**Comment by aaronhallaert** [comment]
Hi, thanks for creating the issues 😉 
This is a good suggestion. I'll see if I can find a worthy alternative for people using `fugitive` instead of `diffview` to keep everything consistent.
Or I could check if `diffview` is present and fall back on the current behavior if it isn't installed (I'm not a fan of forcing people to use plugins).

**Comment by aaronhallaert** [comment]
Seems like `:Gedit commit` does the same thing for `fugitive`
