### ISSUE TITLE
Possible to update the picker view?

### ISSUE THREAD

**Issue by exosyphon** [aaronhallaert/advanced-git-search.nvim#51]
First off, thank you! I really enjoy this plugin and have been using it quite a bit recently.

I'd like to swap out the date of the commit for the author. I wasn't able to see if this is something that is configurable or not.

Format today:
<commit_sha>  <commit_author>  <commit_message>

Desired format:
<commit_sha> <commit_date> <commit_message>

**Comment by aaronhallaert** [comment]
Good suggestion to make it configurable. The only problem I have with it is that the query allows a more targeted search based on author by using `@`, e.g. `my query @Name of author`. When we would manually configure the picker to show the `<commit_date>` and hide the `<commit_author>`, there won't be any feedback anymore on the author search.

I'll have a look at it in the coming days 😉

**Comment by exosyphon** [comment]
Thanks @aaronhallaert! Another option could be to show the date in the preview window somewhere. To my knowledge it doesn't show up there either.

**Comment by aaronhallaert** [comment]
Hi @exosyphon

I like the idea of extending the preview window with additional information. This is something I wanted to do for a long time so I could show extra context to the diff that's shown there. Since both telescope and fzf-lua have the ability to have a neovim buffer in the preview window, it is easy to write some context in that buffer (hash, date, author and the commits that are compared in the preview window).

However, the biggest problem is that writing the output of a command like `git-diff` into a normal neovim buffer is not an easy task without losing color. Luckily there are plugins like https://github.com/m00qek/baleia.nvim that make neovim highlights from ansi codes, which works pretty well. The only problem is we can't use pagers anymore if we do it like that because the standard output is not a terminal (some people are using  [delta](https://github.com/dandavison/delta)) and I don't really like to add an additional dependency. To keep pagers and color without additional plugins, I need something like `vim.fn.termopen`, which makes the buffertype `terminal`, but then I can't write the extra context anymore.

I'll keep you posted if I find a solution 😉

**Comment by aaronhallaert** [comment]
@exosyphon I figured out how to have a neovim buffer which shows a git diff with pager and colors, but it required an extra plugin, I'm going give that another try later.
However, I came up with a solution to show date or author in the picker. I implemented a mapping on the picker to toggle date and author (`<C-w>`). I linked a PR to this issue. Can you give it a try?
